set(vtkCommonCore_LOADED 1)
set(vtkCommonCore_DEPENDS "vtkkwiml;vtksys;vtkutf8")
set(vtkCommonCore_LIBRARIES "vtkCommonCore")
set(vtkCommonCore_INCLUDE_DIRS "C:/Users/user/Documents/BrainX3/vtk-python-openvr/Common/Core;C:/Users/user/Documents/BrainX3/VTK/Common/Core")
set(vtkCommonCore_LIBRARY_DIRS "")
set(vtkCommonCore_RUNTIME_LIBRARY_DIRS "C:/Users/user/Documents/BrainX3/vtk-python-openvr/bin")
set(vtkCommonCore_WRAP_HIERARCHY_FILE "C:/Users/user/Documents/BrainX3/vtk-python-openvr/lib/cmake/vtk-8.2/Modules/vtkCommonCoreHierarchy.txt")
set(vtkCommonCore_KIT "vtkCommon")
set(vtkCommonCore_TARGETS_FILE "")
set(VTK_DEBUG_LEAKS "OFF")
set(VTK_USE_64BIT_IDS "ON")
set(VTK_ALL_NEW_OBJECT_FACTORY "OFF")
set(VTK_USE_64BIT_TIMESTAMPS "")


